[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "risk_return_prediction"
version = "0.1"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["data_analysis", "data_collection"]
